version: '2.2'
services:
  db:
    image: mariadb:10.5.8
    container_name: fd2_mariadb
    volumes:
      - './db:/var/lib/mysql:delegated'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm

  www:
    depends_on:
      - db
    # If there are changes to the Dockerfile update the tag
    # here to force a new build when main is updated.
    image: farmos:fd2.4
    build:
     context: ./farmOS
     dockerfile: Dockerfile
    container_name: fd2_farmdata2
    volumes:
      - './settings.php:/var/www/html/sites/default/settings.php:delegated'
      - './logo:/var/www/html/sites/default/files:cached'
      - '../contrib_modules:/var/www/html/sites/all/modules/contrib_modules:cached'
      - '../farmdata2_modules:/var/www/html/sites/all/modules/farmdata2_modules:cached'
      - './sampleDB:/sampleDB'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1


